### PR TITLE
Replace silk dashboards with static ones

### PR DESCRIPTION
**Pull request by secretrobotron**
silk.co has been shut down, but the creators exported our dashboards before that happened and sent us to them as static files. We need to update this website so that it contains those static dashboards, and changes the urls pointing to silk.co.

### CODE REVIEW

**Comment by alanmoo** [comment]
👋 

As most of this is just an export, is  `wash-dashboards.js` the only file that really needs review?

**Comment by cadecairos** [comment]
@secretrobotron ^

**Comment by secretrobotron** [comment]
> As most of this is just an export, is `wash-dashboards.js` the only file that really needs review?

Yeah. It's a pretty simple tool that just scrapes dashboards and removes stuff from them. Doesn't need a lot of scrutiny, imo.

**Review by alanmoo — APPROVED** [review]
Seems to work for me

**Comment by secretrobotron** [comment]
Thanks @alanmoo ! 😸

**Pull request merged**
